helper with yt auth fails

diff --git a/retitle b/retitle
--- a/retitle
+++ b/retitle
@@ -291,7 +291,7 @@ set_youtube_live_title() {
 		fi
 	fi
 
-	[[ -n "$id" ]] || die 'could not find a YouTube live broadcast to update'
+	[[ -n "$id" ]] || die 'could not find a YouTube live broadcast to update, cache-yt-token?'
 
 	json="$(youtube_get_broadcast "$id")" ||
 		die "could not fetch YouTube broadcast $id"
